name: E2e Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and deploy 
      run: |
        ls
    - name: E2E TEST
      run: |
        docker pull swaponline/dapptestnv
        docker run --shm-size 1G --rm -v ./e2e:/app swaponline/dapptestnv
