name: Test withdraw forms

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'withdraw tests' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build and deploy 
      run: |
        npm i

    - name: TEST
      run: |
        npm run test:unit
      env:
        CI: true
        super_secret: ${{ secrets.buildbot }}
